### ISSUE TITLE
Object.Values error - not supported in Node.js 6.5.x on Windows?

### ISSUE THREAD

**Issue by tatlin** [tdack/unifi-parental#9]
Hi, I'm very excited about this project as it potentially will save me from implementing the same thing for my local Unifi home network. 

I'm trying to test this code using node.js on my Win10 laptop before deploying to a NAS. I see this error when trying to run. I've cleaned the node.js cache, done a full reinstall and the error still persists. any ideas?

A cursory search shows  node.js 6.5.x does not support Object.values?
https://stackoverflow.com/questions/40421825/how-to-use-object-values-on-server-side-in-node-js

> unifi-parental@0.0.5 start C:\Users\mattj\OneDrive\Documents\GitHub\unifi-parental
> node index.js

TypeError: Object.values is not a function
    at Server.spdy.createServer.listen (C:\Users\mattj\OneDrive\Documents\GitHub\unifi-parental\index.js:283:20)
    at Server.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Server.emit (events.js:185:7)
    at Server.emit (C:\Users\mattj\OneDrive\Documents\GitHub\unifi-parental\node_modules\spdy\lib\spdy\server.js:237:40)
    at emitListeningNT (net.js:1284:10)
    at _combinedTickCallback (internal/process/next_tick.js:77:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:389:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! unifi-parental@0.0.5 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the unifi-parental@0.0.5 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\mattj\AppData\Roaming\npm-cache\_logs\2018-12-30T16_27_38_219Z-debug.log

https://stackoverflow.com/questions/40421825/how-to-use-object-values-on-server-side-in-node-js

**Comment by tdack** [comment]
It looks like you are using a pretty old version of NodeJS. This code needs at least v7.10.x or later. There are two LTS at the moment, v8.x and v10.x - see https://github.com/nodejs/Release#release-schedule

You could probably replace the `Object.values(...)` call with a `Object.keys(data).map( k => data[k]).forEach(...)` but I haven't tested it.
